# Buildpack API version
api = "0.5"

# Buildpack ID and metadata
[buildpack]
id = "radiatorspring/neo-buildpack"
version = "0.0.1"
name = "Neo Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "io.buildpacks.stacks.bionic"
