apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: kneo-builder
spec:
  serviceAccount: tutorial-service-account
  tag: dirigiblelabs/kneo-builder
  stack:
    name: kneo-xsk-stack
    kind: ClusterStack
  store:
    name: kneo-xsk-store
    kind: ClusterStore
  order:
  - group:
    - id: dirigiblelabs/kneo-java-buildpack
