apiVersion: kpack.io/v1alpha1
kind: Builder
metadata:
  name: neo-builder
spec:
  serviceAccount: tutorial-service-account
  tag: radiatorspring/neo-builder
  stack:
    name: kneo-xsk-stack
    kind: ClusterStack
  store:
    name: kneo-xsk-store
    kind: ClusterStore
  order:
  - group:
    - id: radiatorspring/neo-buildpack
