site_name: Project XSK
site_url: https://sap.github.io/xsk

nav:
    - Welcome: 'index.md'
    - Artifacts: 
      - hdbtable: 'artifacts/hdbtable.md'
      - hdbview: 'artifacts/hdbview.md'
      - hdbtablefunction: 'artifacts/hdbtablefunction.md'
      - hdbprocedure: 'artifacts/hdbprocedure.md'
      - hdbschema: 'artifacts/hdbschema.md'
      - hdbsynonym: 'artifacts/hdbsynonym.md'
      - hdbdd: 'artifacts/hdbdd.md'
      - hdbcds: 'artifacts/hdbdd.md'
      - hdbsequence: 'artifacts/hdbsequence.md'
      - xsodata: 'artifacts/xsodata.md'
    - API: 
      - $.hdb: 'api/hdb.md'
      - $.import: 'api/import.md'
      - $.net.Destination: 'api/net.Destination.md'
      - $.net.Mail.Part: 'api/net.Mail.Part.md'
      - $.net.Mail: 'api/net.Mail.md'
      - $.net.SMTPConnection: 'api/net.SMTPConnection.md'
      - $.net.http.Client: 'api/net.http.Client.md'
      - $.net.http.Destination: 'api/net.http.Destination.md'
      - $.net.http.Request: 'api/net.http.Request.md'
      - $.net.http: 'api/net.http.md'
      - $.net: 'api/net.md'
      - $.request: 'api/request.md'
      - $.response: 'api/response.md'
      - $.session: 'api/session.md'
      - $.trace: 'api/trace.md'
      - $.util: 'api/util.md'
      - $.util.codec: 'api/util.codec.md'
      - $.web: 'api/web.md'
    - Setup: 
      - Local: 'setup/index.md'
      - Cloud Foundry: 'setup/cloud-foundry.md'
      - Kyma: 'setup/kyma.md'
      - Helm: 'setup/helm.md'
      - Environment Variables: 'setup/environment-variables.md'
    - Community: 'community.md'
    

theme:
  # favicon: /img/favicon.png
  # logo: /img/logo/dirigible-logo.png
  name: mkdocs
  # custom_dir: overrides
  features:
    - navigation.instant
    
# extra_css:
#   - stylesheets/custom.css
#   - stylesheets/homepage.css

markdown_extensions:
    - attr_list
    - pymdownx.snippets
    - pymdownx.highlight:
        linenums: false
    - pymdownx.keys
    - pymdownx.inlinehilite
    - pymdownx.superfences
    - pymdownx.tabbed
    - pymdownx.emoji
    - meta
    - footnotes
    - admonition
    - pymdownx.details

repo_url: https://github.com/sap/xsk
repo_name: sap/xsk
edit_uri: ../../sap/xsk/edit/gh-pages/docs-site/docs/

copyright: Copyright (c) 2021 SAP SE or an SAP affiliate company and XSK contributors.
extra:
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/dirigible_io
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/dirigible.io
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/groups/8413366
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/c/dirigibleio
    - icon: fontawesome/brands/slack
      link: https://eclipse-dirigible.slack.com/

# google_analytics:
#   - UA-49027147-1
#   - auto
