# Default values for XSK
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

docker:
  server:
  username:
  password:
  email:
  secretName: docker-registry-secret
  serviceAccountName: docker-registry-service-account

kyma:
  enabled:
  host:

application:
  image:
  homeUrl:
  imagePullPolicy: Always
  fastBootstrap: false

hana:
  enabled:
  secretName: hana-secret
  url:
  username:
  password:
