# Default values for XSK
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

install:
  clusterBuilder: false
  imageBuilder: false

create:
  image: false
  secret: false
  application: false

docker:
  server:
  username:
  password:
  email:
  secretName: docker-registry-secret
  serviceAccountName: docker-registry-service-account

imageBuilder:
  repository:
  buildpack: dirigiblelabs/kneo-xsk-buildpack

image:
  repository:
  source:
  serviceAccountName: docker-registry-service-account

clusterBuilder:
  buildImage: dirigiblelabs/kneo-xsk-stack-build
  runImage: dirigiblelabs/kneo-xsk-stack-run
  serviceAccountName: docker-registry-service-account

kyma:
  host:

application:
  image:
  homeUrl:
  imagePullPolicy: Always
  fastBootstrap: false

hana:
  secretName: hana-secret
  url:
  username:
  password: