# Stack that will be used by the builder
[stack]
id = "io.buildpacks.stacks.bionic"
# This image is used at runtime
run-image = "radiatorspring/neo-stack-run"
# This image is used at build-time
build-image = "radiatorspring/neo-stack-build"