# Buildpacks to include in builder
[[buildpacks]]
uri = "."

[[order]]
    [[order.group]]
    id = "buildpacks-xsk-kyma"
    version = "latest"

[stack]
id = "com.sap.kneo.xsk"
build-image = "buildpacks-stack-build-xsk-kyma"
run-image = "buildpacks-stack-run-xsk-kyma"
