# Buildpack API version
api = "0.5"

# Buildpack ID and metadata
[buildpack]
id = "buildpacks-xsk-kyma"
version = "latest"
name = "XSK Kyma Buildpack"

# Stacks that the buildpack will work with
[[stacks]]
id = "com.sap.kneo.xsk"
