apiVersion: apps/v1
kind: Deployment
metadata:
  name: dynamic-db
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dynamic-db
  template:
    metadata:
      labels:
        app: dynamic-db
    spec:
      containers:
        - name: dynamic-db
          image: dirigiblelabs/dynamic-db:latest
          env:
            - name: DefaultDB_url
              value: jdbc:sap://<hana-db-url>/<your-db>
            - name: DefaultDB_username
              value: <db-username> # It is DBADMIN by default on HANA
            - name: DefaultDB_password
              value: <db-password>
            - name: DefaultDB_driverClassName
              value: com.sap.db.jdbc.Driver
            - name: DefaultDB_maxWait
              value: "10000"
            - name: DefaultDB_maxIdle
              value: "30"
            - name: DefaultDB_maxActive
              value: "100"
          ports:
            - containerPort: 8080
              name: dynamic-db
---
apiVersion: v1
kind: Service
metadata:
  name: dynamic-db
  namespace: default
  labels:
    app: dynamic-db
spec:
  ports:
    - port: 8080
      name: dynamic-db
  selector:
    app: dynamic-db
