# Buildpacks to include in builder
[[buildpacks]]
uri = "."

[[order]]
    [[order.group]]
    id = "dirigiblelabs/buildpacks-xsk-cf"
    version = "0.0.1"

[stack]
id = "com.sap.kneo.xsk"
build-image = "dirigiblelabs/buildpacks-stack-build-xsk-cf:latest"
run-image = "dirigiblelabs/buildpacks-stack-run-xsk-cf:latest"
