name: Pull Request
on:
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup sapmachine JDK 11
      run: |
        download_url="https://github.com/SAP/SapMachine/releases/download/sapmachine-11.0.11%2B8/sapmachine-jdk-11.0.11-ea.8_linux-x64_bin.tar.gz"
        wget -O "${RUNNER_TEMP}/sapmachine-jdk-11.0.11.tar.gz" "${download_url}"
        tar -xf "${RUNNER_TEMP}/sapmachine-jdk-11.0.11.tar.gz" --directory "${RUNNER_TEMP}"
        export JAVA_HOME="${RUNNER_TEMP}/sapmachine-jdk-11.0.11"
    - name: Maven Build
      run: mvn clean install
