name: Site Build
on:
  push:
    branches: 
      - gh-pages
jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip')"
    steps:
    - uses: actions/checkout@v2
      with:
        token: ${{secrets.GH_TOKEN}}
    - name: Build the site with squidfunk/mkdocs-material container
      run: |
        docker pull squidfunk/mkdocs-material

        # Build
        docker run -v ${{ github.workspace }}/docs-site:/docs squidfunk/mkdocs-material build

        # Clean-up and Copy Build Output
        rm -rf !("charts"|"index.yaml"|"docs-site")
        cp -a docs-site/site/. .
        rm -rf docs-site/site/

    - name: Git Commit and Push
      run: |
        git config user.name ${{secrets.GH_USER_NAME}}
        git config user.email ${{secrets.GH_USER_EMAIL}}
        git add .
        git commit -m "Site content updated - ci skip"
        git push origin gh-pages
